# .rubocop.yml
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

# --- Regras de RSpec ---

# Permite blocos longos (essencial para Describes aninhados)
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/NestedGroups:
  Max: 4

# --- Regras de Gemspec ---

Gemspec/DevelopmentDependencies:
  Enabled: false

# --- Regras Gerais ---

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'